apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: timoni-metrics
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      serviceAccountName: kube-state-metrics
      hostNetwork: true
      hostPID: true
      containers:
        - image: prom/node-exporter:v1.6.1
          args:
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --no-collector.wifi
            - --no-collector.hwmon
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*)$
          name: node-exporter
          ports:
            - containerPort: 9100
              protocol: TCP
              name: scrape
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 102m
              memory: 180Mi
          volumeMounts:
            - mountPath: /host/sys
              mountPropagation: HostToContainer
              name: sys
              readOnly: true
            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: root
              readOnly: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
      volumes:
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /
          name: root
