# example: https://github.com/Altinity/clickhouse-operator/blob/master/docs/chi-examples/99-clickhouseinstallation-max.yaml
# ---

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: timoni-cluster
  namespace: timoni
  labels:
    element: chi-timoni-cluster-timoni-1-0
spec:
  stop: "false"
  restart: RollingUpdate
  defaults:
    templates:
      serviceTemplate: clickhouse-svc-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.timoni
          port: 2181
      session_timeout_ms: 30_000
      operation_timeout_ms: 10_000
    clusters:
      - name: timoni
        layout:
          shardsCount: 2
          replicasCount: 1
        templates:
          podTemplate: clickhouse-pod-template
          dataVolumeClaimTemplate: data-vc-template
          logVolumeClaimTemplate: logs-vc-template
    users:
      default/access_management: 1
      # timoni/password: timoni
      timoni/password_sha256_hex: f5a2a1a6c96ea890a5b6f44f18cc4663630e4f0fc37595aadb33c275467e7a92
      timoni/access_management: 1
      timoni/networks/ip: ::/0
    profiles:
      default/max_insert_threads: 12
      default/optimize_on_insert: 0
      default/max_query_size: 10485760
      default/distributed_directory_monitor_batch_inserts: 1
      default/load_balancing: round_robin
      # default/skip_unavailable_shards: 1
    settings:
      max_connections: 20_000
      # max_concurrent_queries: 1_000 # i don't think it's needed
    files:
      metrics.xml: |
        <yandex>
          <prometheus>
            <endpoint>/metrics</endpoint>
            <port>9363</port>
            <metrics>true</metrics>
            <events>true</events>
            <asynchronous_metrics>true</asynchronous_metrics>
            <status_info>true</status_info>
          </prometheus>
        </yandex>
  templates:
    serviceTemplates:
      - name: clickhouse-svc-template
        # generateName: "clickhouse-{chi}"
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: metrics
              port: 9363
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.1.3.5-alpine
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "3Gi"
                  cpu: "1000m"
        # podDistribution:
        #   - type: ShardAntiAffinity # by shard name - one replica of a shard instance per topologyKey
        #   - type: MaxNumberPerNode
        #     number: 2
        #     topologyKey: "kubernetes.io/hostname"
    volumeClaimTemplates:
      - name: data-vc-template
        spec:
          storageClassName: {{storageClassName}}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Gi"
      - name: logs-vc-template
        spec:
          storageClassName: {{storageClassName}}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "100Mi"
