apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: redis
  namespace: timoni-metrics
spec:
  selector:
    matchLabels:
      element: redis
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: p9121
