apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: mariadb
  namespace: timoni-metrics
spec:
  selector:
    matchLabels:
      element: mariadb
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: p9104
