apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kube-state-metrics
  namespace: timoni-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  podMetricsEndpoints:
    - port: http-metrics
      scheme: http
