apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: timoni-metrics
spec:
  ports:
    - port: 8481
      targetPort: 8481
      protocol: TCP
  selector:
    app.kubernetes.io/name: vmselect
